-- One-time bulk action: check in every delegate named in the reviewed
-- attendee list, for today. Matched by normalized name within the active
-- event; additive and idempotent via the same (delegate_id, check_in_date)
-- uniqueness the rest of the multi-day feature relies on, so re-running
-- this (or a real desk check-in happening for the same person today)
-- never double-books anyone. Mirrors check_in_delegate's own behavior:
-- sets status to checked_in and auto-marks the tag (first time only).
with target_names (full_name) as (
  values
    ('AARON GITONGA'),
    ('Adannuh Golo Ibrahim'),
    ('Adeline Mmbone'),
    ('Adson Meme'),
    ('ALBERT KIPRUTO'),
    ('Alex Gachanja'),
    ('ALEX OTIENO'),
    ('ALEX WAINAINA'),
    ('Alexander Kamunyu'),
    ('ALLAN MACHARIA'),
    ('Allan Muthui'),
    ('AMON KIPKEU'),
    ('AMY NAMWAKIRA'),
    ('ANDREW KOILA'),
    ('Andrew Mugo Warurua'),
    ('Angeline Mwende Muthoka'),
    ('Anthony Balozi'),
    ('ANTHONY KIMONDO'),
    ('ANTHONY LOMONG'),
    ('ANTHONY NJUGUNA'),
    ('ARCH Annah Musyimi'),
    ('Arch David waudo'),
    ('Arch Erastus Ndungu Kamau'),
    ('Arch Milgo Nancy'),
    ('Arch Peter Wanyoike'),
    ('Arch Victor King''e'),
    ('ARCH. (DR) MARTIN MBIDHI, PHD'),
    ('ARCH. BERNARD SEGECHA'),
    ('ARCH. BRENDA NYAWARA'),
    ('Arch. Kyaka Kyalo'),
    ('ARCH. MICHAEL MATHENGE'),
    ('Arch. Yassin Munyanya'),
    ('Assumptor Muthama'),
    ('Atho Mamo'),
    ('Audrey Alicia'),
    ('Audrey Kirui'),
    ('Beatrice Bagada'),
    ('BENJAMIN MUHANDO'),
    ('Benson Gitonga'),
    ('Benson Maina'),
    ('Betty Maithya'),
    ('BILLY NJERU'),
    ('BRANDON KISANGI'),
    ('Brenda Waruinu'),
    ('Brian Chege Mwaura'),
    ('BRIAN TOROITICH'),
    ('Bwire Wycliffe'),
    ('CALEB AMBWAYA'),
    ('Caroline Chege'),
    ('CAROLINE MITAU'),
    ('CHARISSE GRAY'),
    ('CHARLES EKASIBA'),
    ('CHARLES KYETI'),
    ('Charles Manduku'),
    ('Charles Mutunga'),
    ('Charles Nzioka'),
    ('Christopher Tarus'),
    ('COSMAS ONYANGO ODHIAMBO'),
    ('CYPRIAN CHOGE'),
    ('Daniel Agola'),
    ('Daniel Kiprotich'),
    ('DANIEL WANYEKI'),
    ('David K Njenga'),
    ('DAVID KANJA'),
    ('DAVID LAGAT'),
    ('DAVID MATHU'),
    ('DENNIS MURANGIRI'),
    ('Dennis Sinei'),
    ('Desmond Agallo'),
    ('Diana Mumbua Musyoka'),
    ('Dickson Chepcher'),
    ('Dishon Murathe'),
    ('DOMINIC KIYENG'),
    ('Dr James Mwitari'),
    ('DR. L. ARCH. SUNDAY ABUJE'),
    ('DR. LINDA GICHUYIA'),
    ('DR. MARGARITA GARFIAS ROYO'),
    ('DUNCAN MULIANDE IMBAMBA'),
    ('DUNCAN OMUTICHI'),
    ('DUNSTAN NAMASWA'),
    ('Edgar Ayier'),
    ('EDITH ODUOR'),
    ('EDWARD GITHINJI'),
    ('Elizabeth Musila'),
    ('EMMA LUKOSI'),
    ('Eng Anthony Joushua Mugo'),
    ('ENG Catherinne Karue'),
    ('ENG Karani Njeru'),
    ('ENG. HOWARD M’MAYI'),
    ('ENG. NASHON TAMBO'),
    ('ERIC MIANO'),
    ('Erick Edwin'),
    ('ERICK MACHARIA'),
    ('EVELYNE KISATO'),
    ('EVERLYN IRUNGU'),
    ('FAITH ODHIAMBO'),
    ('FESTUS MARIERA'),
    ('FLORENCE NYOLE'),
    ('Francis Maina Njoroge'),
    ('Francis Owade'),
    ('FREDRICK MULAKU'),
    ('Gabriel Wekesa Kibiriti'),
    ('GABRIELLE JEPKIRUI'),
    ('George Arabbu Ndege'),
    ('George C Omondi'),
    ('GEORGE WEKESA'),
    ('GLORIA CHELANGAT'),
    ('Godfrey Mbuya'),
    ('Grace Muendo'),
    ('HAM WESONGA'),
    ('HARON GEKONGE NYAKUNDI'),
    ('HARRIS MULUSA'),
    ('Hellen Ouko'),
    ('Imtiaz Osman'),
    ('Irene Gikera'),
    ('IRENE NAILANTEI'),
    ('Irene Ndunge Musyoka'),
    ('ISAAC NYAMWENO'),
    ('Isabella Mugure'),
    ('JACINTA SEREM'),
    ('Jackline Karagai'),
    ('Jacqueline Kairu'),
    ('JACQUELYNE LEGISHION'),
    ('James Kahare'),
    ('JAMES MUHANJI'),
    ('JAMES MUSOMA'),
    ('Jamila Chelagat'),
    ('JARED KINARO'),
    ('JARED OLUOCH'),
    ('JARED OTIENO'),
    ('JASON MUTHAMIA MWENDA'),
    ('JEFFREY MBUGUA KARERI'),
    ('Jerry Kisaka'),
    ('JESSICAH NYAMBURA GICHUKI'),
    ('JOHN GITHUI'),
    ('JOHN KAEKE'),
    ('JOHN MUGO'),
    ('JOHN MWANIKI'),
    ('JOHNSON MWANGI MAINA'),
    ('JOHNSTONE ACHANDO'),
    ('JOSEPH NDIRANGU'),
    ('Joshua Kariguh'),
    ('Joshua Mayaka'),
    ('JOSPHAT MUNENE'),
    ('JOSPHAT NGUNDO'),
    ('Judith Mutai'),
    ('JULIANNE KIROGO'),
    ('JULIET KABERE'),
    ('Julius Mutunga'),
    ('JUSTINE MAYAKA'),
    ('KANYARU MOSES KARANI'),
    ('KENNEDY MUNYIRI'),
    ('Kenneth Nyaseda'),
    ('KEPHER MANANI'),
    ('Kerry Sikolia'),
    ('Kevin Khisa'),
    ('KEVIN SYENGO'),
    ('KHADIJA HARIZ'),
    ('KHALILA ALI'),
    ('Kimata KIARIE'),
    ('KIMBERLY MONG’ARE'),
    ('KITHAKYE DAVID'),
    ('KYENGO MARTIN'),
    ('L.ARCH. RUTH WANJIKU'),
    ('Laura Lukelesia'),
    ('LAWRENCE MUTISYA'),
    ('Leah Njeri Muriithi'),
    ('LENAH KETOYO'),
    ('Leonard Kuria'),
    ('LINUS KIBISU'),
    ('Ls G. Ngaruiye'),
    ('LUCAS ADWERA'),
    ('LUCY KIMANI'),
    ('M.ARCH. ROY GITHAIGA'),
    ('MAJ J MESO'),
    ('MARGDALYN KWAMBOKA'),
    ('MARIA WANJIKU GICHEHA'),
    ('MARTHA WANGUI'),
    ('Martin Kubai'),
    ('Martin waweru'),
    ('MARY ANDIKA'),
    ('Matias Ndonga Kabiru'),
    ('MATILDA NIMATSUTSU'),
    ('Maureen Mulang’a'),
    ('Maureen Mulang''a'),
    ('Melissa Kasaba'),
    ('MERCY ATEKA'),
    ('Mercy Kirema'),
    ('MICHAEL KYEVA'),
    ('Michael Nderitu'),
    ('Michael Odhiambo Okumu'),
    ('Michael Wanjohi'),
    ('MICHELLE OUMA'),
    ('MIKE IRAVO'),
    ('Mike Mutunga'),
    ('Millicent cherotich'),
    ('Miriam Mutunga'),
    ('MOHAMED MUNYANYA'),
    ('Mohamed Said'),
    ('MOHAMMED ALI MWENJE'),
    ('MOHAMMED HASSAN BARE'),
    ('Morris Muiruri Murigi'),
    ('MORRIS YAVI'),
    ('MOSES AKIDADI'),
    ('MOSES KIPTUI'),
    ('Moses Makori'),
    ('Muguru Wairimu'),
    ('Muhammad Ali'),
    ('Mutua Urbanos'),
    ('Mwongera Rukaria'),
    ('Naomi Achieng'''),
    ('NATHANIEL NGUITHI'),
    ('Ndindiri Waweru'),
    ('NELLY AGOLA'),
    ('NEROUS MUTCHERE'),
    ('NICHOLAS KIOGORA'),
    ('Nicholas Nyona'),
    ('Nicholas Onyango'),
    ('Nick Mungai'),
    ('NISHA VAN HOEK'),
    ('Obutu Ivan Magori'),
    ('Ogada Alice Awuor'),
    ('OGEMBO ENOCK'),
    ('OGUTU CYRUS'),
    ('Ojwang Bernard'),
    ('Oliver Chapa'),
    ('ONESMUS KAKOI MWATU'),
    ('Patricia Baariu'),
    ('Patrick Kathuli'),
    ('Patrick Mugo'),
    ('PATRICK OYONDI'),
    ('PAUL AYODI'),
    ('PAUL KARARA'),
    ('Paul Mumo'),
    ('PAUL MUTHOKA'),
    ('PAUL OUMA'),
    ('PAULINE MWASHI'),
    ('peninah omanwa'),
    ('PETER KANYI'),
    ('Peter Miriti'),
    ('Peter Njeru'),
    ('Philip Osoro Amwata'),
    ('Phires Ogoti'),
    ('Plan David Ore'),
    ('PLAN SIMON NJOROGE KAMAU'),
    ('PLAN. CHRISTINE MUCHIRI'),
    ('PROF TOM ANYAMBA'),
    ('Qs Morris Mwiti'),
    ('QS MUTINDA MUTUKU'),
    ('QS. AUDILY CHATORA'),
    ('QS. DAVID AGANYO NYANGAU'),
    ('QUEENVELLY MAYAKA'),
    ('REDEMPTA MUNYALO'),
    ('REHEMA JAYSHREE'),
    ('Restepice Rammoko'),
    ('Rither Chepkemoi'),
    ('ROBERT KIGGUNDU'),
    ('RODAH BOYANI'),
    ('RODGERS MWENDA'),
    ('RONALD MURIUKI'),
    ('ROSE KAGECHI WAWERU'),
    ('ROSEBRENDA MUCHIGA'),
    ('Roy Guda'),
    ('RUTH MAKAU'),
    ('Ryan Losieku'),
    ('SAMSON MAINA'),
    ('Samson Mutune'),
    ('Samuel Githae'),
    ('SAMUEL KIAI'),
    ('Sarah Kibe'),
    ('SAVIA MJOMBA'),
    ('SCOTT WAITHAKA'),
    ('Serah Chege'),
    ('SHARON TANUI'),
    ('SHEILA JEPKORIRI TANUI'),
    ('SHEILA OKONGO'),
    ('Silvester Muli'),
    ('SIMON KAGOTHO'),
    ('Solomon Were'),
    ('Stanley Gado'),
    ('Stanley Karanja'),
    ('Stanley Kyalo'),
    ('STANLEY NGENY'),
    ('STEPHEN MUCHERU'),
    ('STEPHEN MUTISO'),
    ('STEPHEN MWILU'),
    ('Steve Gome'),
    ('STEVE MAHONGA'),
    ('SUSAN NJERI KIBUE'),
    ('SYLVIA ESSENDI'),
    ('SYMMON KIDERO'),
    ('Syrone Owuor Otieno'),
    ('TAMASHA WAMBUI NDUNG’U'),
    ('TOBIAS JOSEPH'),
    ('Tuesday Nyakango'),
    ('Valerie Gatwiri Irungu'),
    ('Victor Bielesie'),
    ('VICTOR KANYAURA'),
    ('VICTOR KIVAYA'),
    ('VICTOR NJIRU'),
    ('VICTORIA BANCHIRI'),
    ('Viola Adhiambo Sigu'),
    ('VIOLET BAGADA'),
    ('Vivian Wambui Thairu'),
    ('Wageita Peter Munyua'),
    ('WAMBAA MUNGAI'),
    ('WELLINGTON SINDANI'),
    ('Wendy Kihiu'),
    ('Wesly Asubwa'),
    ('WILLIAM MAMBO MATOLA'),
    ('Wilson Mugambi'),
    ('WILSON NYANGE'),
    ('Winfrida Wanjiku Ngumi'),
    ('WINNIE KALYA'),
    ('WINSTON SHIMIRWA'),
    ('WYCLIFFE OMARIBA'),
    ('ZAWADI NDUNG’U')
),
matched as (
  select distinct d.id as delegate_id, d.event_id
  from public.delegates d
  join target_names t on public.normalize_name(d.full_name) = public.normalize_name(t.full_name)
  where d.event_id = public.active_event_id()
),
inserted as (
  insert into public.check_ins (delegate_id, event_id, check_in_date, checked_in_by, method, device_label)
  select delegate_id, event_id, (now() at time zone 'Africa/Nairobi')::date, null, 'search', 'Bulk check-in from attendee list'
  from matched
  on conflict (delegate_id, check_in_date) do nothing
  returning delegate_id
)
update public.delegates d
set status = 'checked_in',
    tag_issued_at = coalesce(d.tag_issued_at, now())
where d.id in (select delegate_id from matched);

do $$
declare
  v_target_count int;
  v_matched_count int;
begin
  select count(*) into v_target_count from (values
    ('AARON GITONGA'),
    ('Adannuh Golo Ibrahim'),
    ('Adeline Mmbone'),
    ('Adson Meme'),
    ('ALBERT KIPRUTO'),
    ('Alex Gachanja'),
    ('ALEX OTIENO'),
    ('ALEX WAINAINA'),
    ('Alexander Kamunyu'),
    ('ALLAN MACHARIA'),
    ('Allan Muthui'),
    ('AMON KIPKEU'),
    ('AMY NAMWAKIRA'),
    ('ANDREW KOILA'),
    ('Andrew Mugo Warurua'),
    ('Angeline Mwende Muthoka'),
    ('Anthony Balozi'),
    ('ANTHONY KIMONDO'),
    ('ANTHONY LOMONG'),
    ('ANTHONY NJUGUNA'),
    ('ARCH Annah Musyimi'),
    ('Arch David waudo'),
    ('Arch Erastus Ndungu Kamau'),
    ('Arch Milgo Nancy'),
    ('Arch Peter Wanyoike'),
    ('Arch Victor King''e'),
    ('ARCH. (DR) MARTIN MBIDHI, PHD'),
    ('ARCH. BERNARD SEGECHA'),
    ('ARCH. BRENDA NYAWARA'),
    ('Arch. Kyaka Kyalo'),
    ('ARCH. MICHAEL MATHENGE'),
    ('Arch. Yassin Munyanya'),
    ('Assumptor Muthama'),
    ('Atho Mamo'),
    ('Audrey Alicia'),
    ('Audrey Kirui'),
    ('Beatrice Bagada'),
    ('BENJAMIN MUHANDO'),
    ('Benson Gitonga'),
    ('Benson Maina'),
    ('Betty Maithya'),
    ('BILLY NJERU'),
    ('BRANDON KISANGI'),
    ('Brenda Waruinu'),
    ('Brian Chege Mwaura'),
    ('BRIAN TOROITICH'),
    ('Bwire Wycliffe'),
    ('CALEB AMBWAYA'),
    ('Caroline Chege'),
    ('CAROLINE MITAU'),
    ('CHARISSE GRAY'),
    ('CHARLES EKASIBA'),
    ('CHARLES KYETI'),
    ('Charles Manduku'),
    ('Charles Mutunga'),
    ('Charles Nzioka'),
    ('Christopher Tarus'),
    ('COSMAS ONYANGO ODHIAMBO'),
    ('CYPRIAN CHOGE'),
    ('Daniel Agola'),
    ('Daniel Kiprotich'),
    ('DANIEL WANYEKI'),
    ('David K Njenga'),
    ('DAVID KANJA'),
    ('DAVID LAGAT'),
    ('DAVID MATHU'),
    ('DENNIS MURANGIRI'),
    ('Dennis Sinei'),
    ('Desmond Agallo'),
    ('Diana Mumbua Musyoka'),
    ('Dickson Chepcher'),
    ('Dishon Murathe'),
    ('DOMINIC KIYENG'),
    ('Dr James Mwitari'),
    ('DR. L. ARCH. SUNDAY ABUJE'),
    ('DR. LINDA GICHUYIA'),
    ('DR. MARGARITA GARFIAS ROYO'),
    ('DUNCAN MULIANDE IMBAMBA'),
    ('DUNCAN OMUTICHI'),
    ('DUNSTAN NAMASWA'),
    ('Edgar Ayier'),
    ('EDITH ODUOR'),
    ('EDWARD GITHINJI'),
    ('Elizabeth Musila'),
    ('EMMA LUKOSI'),
    ('Eng Anthony Joushua Mugo'),
    ('ENG Catherinne Karue'),
    ('ENG Karani Njeru'),
    ('ENG. HOWARD M’MAYI'),
    ('ENG. NASHON TAMBO'),
    ('ERIC MIANO'),
    ('Erick Edwin'),
    ('ERICK MACHARIA'),
    ('EVELYNE KISATO'),
    ('EVERLYN IRUNGU'),
    ('FAITH ODHIAMBO'),
    ('FESTUS MARIERA'),
    ('FLORENCE NYOLE'),
    ('Francis Maina Njoroge'),
    ('Francis Owade'),
    ('FREDRICK MULAKU'),
    ('Gabriel Wekesa Kibiriti'),
    ('GABRIELLE JEPKIRUI'),
    ('George Arabbu Ndege'),
    ('George C Omondi'),
    ('GEORGE WEKESA'),
    ('GLORIA CHELANGAT'),
    ('Godfrey Mbuya'),
    ('Grace Muendo'),
    ('HAM WESONGA'),
    ('HARON GEKONGE NYAKUNDI'),
    ('HARRIS MULUSA'),
    ('Hellen Ouko'),
    ('Imtiaz Osman'),
    ('Irene Gikera'),
    ('IRENE NAILANTEI'),
    ('Irene Ndunge Musyoka'),
    ('ISAAC NYAMWENO'),
    ('Isabella Mugure'),
    ('JACINTA SEREM'),
    ('Jackline Karagai'),
    ('Jacqueline Kairu'),
    ('JACQUELYNE LEGISHION'),
    ('James Kahare'),
    ('JAMES MUHANJI'),
    ('JAMES MUSOMA'),
    ('Jamila Chelagat'),
    ('JARED KINARO'),
    ('JARED OLUOCH'),
    ('JARED OTIENO'),
    ('JASON MUTHAMIA MWENDA'),
    ('JEFFREY MBUGUA KARERI'),
    ('Jerry Kisaka'),
    ('JESSICAH NYAMBURA GICHUKI'),
    ('JOHN GITHUI'),
    ('JOHN KAEKE'),
    ('JOHN MUGO'),
    ('JOHN MWANIKI'),
    ('JOHNSON MWANGI MAINA'),
    ('JOHNSTONE ACHANDO'),
    ('JOSEPH NDIRANGU'),
    ('Joshua Kariguh'),
    ('Joshua Mayaka'),
    ('JOSPHAT MUNENE'),
    ('JOSPHAT NGUNDO'),
    ('Judith Mutai'),
    ('JULIANNE KIROGO'),
    ('JULIET KABERE'),
    ('Julius Mutunga'),
    ('JUSTINE MAYAKA'),
    ('KANYARU MOSES KARANI'),
    ('KENNEDY MUNYIRI'),
    ('Kenneth Nyaseda'),
    ('KEPHER MANANI'),
    ('Kerry Sikolia'),
    ('Kevin Khisa'),
    ('KEVIN SYENGO'),
    ('KHADIJA HARIZ'),
    ('KHALILA ALI'),
    ('Kimata KIARIE'),
    ('KIMBERLY MONG’ARE'),
    ('KITHAKYE DAVID'),
    ('KYENGO MARTIN'),
    ('L.ARCH. RUTH WANJIKU'),
    ('Laura Lukelesia'),
    ('LAWRENCE MUTISYA'),
    ('Leah Njeri Muriithi'),
    ('LENAH KETOYO'),
    ('Leonard Kuria'),
    ('LINUS KIBISU'),
    ('Ls G. Ngaruiye'),
    ('LUCAS ADWERA'),
    ('LUCY KIMANI'),
    ('M.ARCH. ROY GITHAIGA'),
    ('MAJ J MESO'),
    ('MARGDALYN KWAMBOKA'),
    ('MARIA WANJIKU GICHEHA'),
    ('MARTHA WANGUI'),
    ('Martin Kubai'),
    ('Martin waweru'),
    ('MARY ANDIKA'),
    ('Matias Ndonga Kabiru'),
    ('MATILDA NIMATSUTSU'),
    ('Maureen Mulang’a'),
    ('Maureen Mulang''a'),
    ('Melissa Kasaba'),
    ('MERCY ATEKA'),
    ('Mercy Kirema'),
    ('MICHAEL KYEVA'),
    ('Michael Nderitu'),
    ('Michael Odhiambo Okumu'),
    ('Michael Wanjohi'),
    ('MICHELLE OUMA'),
    ('MIKE IRAVO'),
    ('Mike Mutunga'),
    ('Millicent cherotich'),
    ('Miriam Mutunga'),
    ('MOHAMED MUNYANYA'),
    ('Mohamed Said'),
    ('MOHAMMED ALI MWENJE'),
    ('MOHAMMED HASSAN BARE'),
    ('Morris Muiruri Murigi'),
    ('MORRIS YAVI'),
    ('MOSES AKIDADI'),
    ('MOSES KIPTUI'),
    ('Moses Makori'),
    ('Muguru Wairimu'),
    ('Muhammad Ali'),
    ('Mutua Urbanos'),
    ('Mwongera Rukaria'),
    ('Naomi Achieng'''),
    ('NATHANIEL NGUITHI'),
    ('Ndindiri Waweru'),
    ('NELLY AGOLA'),
    ('NEROUS MUTCHERE'),
    ('NICHOLAS KIOGORA'),
    ('Nicholas Nyona'),
    ('Nicholas Onyango'),
    ('Nick Mungai'),
    ('NISHA VAN HOEK'),
    ('Obutu Ivan Magori'),
    ('Ogada Alice Awuor'),
    ('OGEMBO ENOCK'),
    ('OGUTU CYRUS'),
    ('Ojwang Bernard'),
    ('Oliver Chapa'),
    ('ONESMUS KAKOI MWATU'),
    ('Patricia Baariu'),
    ('Patrick Kathuli'),
    ('Patrick Mugo'),
    ('PATRICK OYONDI'),
    ('PAUL AYODI'),
    ('PAUL KARARA'),
    ('Paul Mumo'),
    ('PAUL MUTHOKA'),
    ('PAUL OUMA'),
    ('PAULINE MWASHI'),
    ('peninah omanwa'),
    ('PETER KANYI'),
    ('Peter Miriti'),
    ('Peter Njeru'),
    ('Philip Osoro Amwata'),
    ('Phires Ogoti'),
    ('Plan David Ore'),
    ('PLAN SIMON NJOROGE KAMAU'),
    ('PLAN. CHRISTINE MUCHIRI'),
    ('PROF TOM ANYAMBA'),
    ('Qs Morris Mwiti'),
    ('QS MUTINDA MUTUKU'),
    ('QS. AUDILY CHATORA'),
    ('QS. DAVID AGANYO NYANGAU'),
    ('QUEENVELLY MAYAKA'),
    ('REDEMPTA MUNYALO'),
    ('REHEMA JAYSHREE'),
    ('Restepice Rammoko'),
    ('Rither Chepkemoi'),
    ('ROBERT KIGGUNDU'),
    ('RODAH BOYANI'),
    ('RODGERS MWENDA'),
    ('RONALD MURIUKI'),
    ('ROSE KAGECHI WAWERU'),
    ('ROSEBRENDA MUCHIGA'),
    ('Roy Guda'),
    ('RUTH MAKAU'),
    ('Ryan Losieku'),
    ('SAMSON MAINA'),
    ('Samson Mutune'),
    ('Samuel Githae'),
    ('SAMUEL KIAI'),
    ('Sarah Kibe'),
    ('SAVIA MJOMBA'),
    ('SCOTT WAITHAKA'),
    ('Serah Chege'),
    ('SHARON TANUI'),
    ('SHEILA JEPKORIRI TANUI'),
    ('SHEILA OKONGO'),
    ('Silvester Muli'),
    ('SIMON KAGOTHO'),
    ('Solomon Were'),
    ('Stanley Gado'),
    ('Stanley Karanja'),
    ('Stanley Kyalo'),
    ('STANLEY NGENY'),
    ('STEPHEN MUCHERU'),
    ('STEPHEN MUTISO'),
    ('STEPHEN MWILU'),
    ('Steve Gome'),
    ('STEVE MAHONGA'),
    ('SUSAN NJERI KIBUE'),
    ('SYLVIA ESSENDI'),
    ('SYMMON KIDERO'),
    ('Syrone Owuor Otieno'),
    ('TAMASHA WAMBUI NDUNG’U'),
    ('TOBIAS JOSEPH'),
    ('Tuesday Nyakango'),
    ('Valerie Gatwiri Irungu'),
    ('Victor Bielesie'),
    ('VICTOR KANYAURA'),
    ('VICTOR KIVAYA'),
    ('VICTOR NJIRU'),
    ('VICTORIA BANCHIRI'),
    ('Viola Adhiambo Sigu'),
    ('VIOLET BAGADA'),
    ('Vivian Wambui Thairu'),
    ('Wageita Peter Munyua'),
    ('WAMBAA MUNGAI'),
    ('WELLINGTON SINDANI'),
    ('Wendy Kihiu'),
    ('Wesly Asubwa'),
    ('WILLIAM MAMBO MATOLA'),
    ('Wilson Mugambi'),
    ('WILSON NYANGE'),
    ('Winfrida Wanjiku Ngumi'),
    ('WINNIE KALYA'),
    ('WINSTON SHIMIRWA'),
    ('WYCLIFFE OMARIBA'),
    ('ZAWADI NDUNG’U')
  ) as t(full_name);
  select count(distinct d.id) into v_matched_count
    from public.delegates d
    join (values
    ('AARON GITONGA'),
    ('Adannuh Golo Ibrahim'),
    ('Adeline Mmbone'),
    ('Adson Meme'),
    ('ALBERT KIPRUTO'),
    ('Alex Gachanja'),
    ('ALEX OTIENO'),
    ('ALEX WAINAINA'),
    ('Alexander Kamunyu'),
    ('ALLAN MACHARIA'),
    ('Allan Muthui'),
    ('AMON KIPKEU'),
    ('AMY NAMWAKIRA'),
    ('ANDREW KOILA'),
    ('Andrew Mugo Warurua'),
    ('Angeline Mwende Muthoka'),
    ('Anthony Balozi'),
    ('ANTHONY KIMONDO'),
    ('ANTHONY LOMONG'),
    ('ANTHONY NJUGUNA'),
    ('ARCH Annah Musyimi'),
    ('Arch David waudo'),
    ('Arch Erastus Ndungu Kamau'),
    ('Arch Milgo Nancy'),
    ('Arch Peter Wanyoike'),
    ('Arch Victor King''e'),
    ('ARCH. (DR) MARTIN MBIDHI, PHD'),
    ('ARCH. BERNARD SEGECHA'),
    ('ARCH. BRENDA NYAWARA'),
    ('Arch. Kyaka Kyalo'),
    ('ARCH. MICHAEL MATHENGE'),
    ('Arch. Yassin Munyanya'),
    ('Assumptor Muthama'),
    ('Atho Mamo'),
    ('Audrey Alicia'),
    ('Audrey Kirui'),
    ('Beatrice Bagada'),
    ('BENJAMIN MUHANDO'),
    ('Benson Gitonga'),
    ('Benson Maina'),
    ('Betty Maithya'),
    ('BILLY NJERU'),
    ('BRANDON KISANGI'),
    ('Brenda Waruinu'),
    ('Brian Chege Mwaura'),
    ('BRIAN TOROITICH'),
    ('Bwire Wycliffe'),
    ('CALEB AMBWAYA'),
    ('Caroline Chege'),
    ('CAROLINE MITAU'),
    ('CHARISSE GRAY'),
    ('CHARLES EKASIBA'),
    ('CHARLES KYETI'),
    ('Charles Manduku'),
    ('Charles Mutunga'),
    ('Charles Nzioka'),
    ('Christopher Tarus'),
    ('COSMAS ONYANGO ODHIAMBO'),
    ('CYPRIAN CHOGE'),
    ('Daniel Agola'),
    ('Daniel Kiprotich'),
    ('DANIEL WANYEKI'),
    ('David K Njenga'),
    ('DAVID KANJA'),
    ('DAVID LAGAT'),
    ('DAVID MATHU'),
    ('DENNIS MURANGIRI'),
    ('Dennis Sinei'),
    ('Desmond Agallo'),
    ('Diana Mumbua Musyoka'),
    ('Dickson Chepcher'),
    ('Dishon Murathe'),
    ('DOMINIC KIYENG'),
    ('Dr James Mwitari'),
    ('DR. L. ARCH. SUNDAY ABUJE'),
    ('DR. LINDA GICHUYIA'),
    ('DR. MARGARITA GARFIAS ROYO'),
    ('DUNCAN MULIANDE IMBAMBA'),
    ('DUNCAN OMUTICHI'),
    ('DUNSTAN NAMASWA'),
    ('Edgar Ayier'),
    ('EDITH ODUOR'),
    ('EDWARD GITHINJI'),
    ('Elizabeth Musila'),
    ('EMMA LUKOSI'),
    ('Eng Anthony Joushua Mugo'),
    ('ENG Catherinne Karue'),
    ('ENG Karani Njeru'),
    ('ENG. HOWARD M’MAYI'),
    ('ENG. NASHON TAMBO'),
    ('ERIC MIANO'),
    ('Erick Edwin'),
    ('ERICK MACHARIA'),
    ('EVELYNE KISATO'),
    ('EVERLYN IRUNGU'),
    ('FAITH ODHIAMBO'),
    ('FESTUS MARIERA'),
    ('FLORENCE NYOLE'),
    ('Francis Maina Njoroge'),
    ('Francis Owade'),
    ('FREDRICK MULAKU'),
    ('Gabriel Wekesa Kibiriti'),
    ('GABRIELLE JEPKIRUI'),
    ('George Arabbu Ndege'),
    ('George C Omondi'),
    ('GEORGE WEKESA'),
    ('GLORIA CHELANGAT'),
    ('Godfrey Mbuya'),
    ('Grace Muendo'),
    ('HAM WESONGA'),
    ('HARON GEKONGE NYAKUNDI'),
    ('HARRIS MULUSA'),
    ('Hellen Ouko'),
    ('Imtiaz Osman'),
    ('Irene Gikera'),
    ('IRENE NAILANTEI'),
    ('Irene Ndunge Musyoka'),
    ('ISAAC NYAMWENO'),
    ('Isabella Mugure'),
    ('JACINTA SEREM'),
    ('Jackline Karagai'),
    ('Jacqueline Kairu'),
    ('JACQUELYNE LEGISHION'),
    ('James Kahare'),
    ('JAMES MUHANJI'),
    ('JAMES MUSOMA'),
    ('Jamila Chelagat'),
    ('JARED KINARO'),
    ('JARED OLUOCH'),
    ('JARED OTIENO'),
    ('JASON MUTHAMIA MWENDA'),
    ('JEFFREY MBUGUA KARERI'),
    ('Jerry Kisaka'),
    ('JESSICAH NYAMBURA GICHUKI'),
    ('JOHN GITHUI'),
    ('JOHN KAEKE'),
    ('JOHN MUGO'),
    ('JOHN MWANIKI'),
    ('JOHNSON MWANGI MAINA'),
    ('JOHNSTONE ACHANDO'),
    ('JOSEPH NDIRANGU'),
    ('Joshua Kariguh'),
    ('Joshua Mayaka'),
    ('JOSPHAT MUNENE'),
    ('JOSPHAT NGUNDO'),
    ('Judith Mutai'),
    ('JULIANNE KIROGO'),
    ('JULIET KABERE'),
    ('Julius Mutunga'),
    ('JUSTINE MAYAKA'),
    ('KANYARU MOSES KARANI'),
    ('KENNEDY MUNYIRI'),
    ('Kenneth Nyaseda'),
    ('KEPHER MANANI'),
    ('Kerry Sikolia'),
    ('Kevin Khisa'),
    ('KEVIN SYENGO'),
    ('KHADIJA HARIZ'),
    ('KHALILA ALI'),
    ('Kimata KIARIE'),
    ('KIMBERLY MONG’ARE'),
    ('KITHAKYE DAVID'),
    ('KYENGO MARTIN'),
    ('L.ARCH. RUTH WANJIKU'),
    ('Laura Lukelesia'),
    ('LAWRENCE MUTISYA'),
    ('Leah Njeri Muriithi'),
    ('LENAH KETOYO'),
    ('Leonard Kuria'),
    ('LINUS KIBISU'),
    ('Ls G. Ngaruiye'),
    ('LUCAS ADWERA'),
    ('LUCY KIMANI'),
    ('M.ARCH. ROY GITHAIGA'),
    ('MAJ J MESO'),
    ('MARGDALYN KWAMBOKA'),
    ('MARIA WANJIKU GICHEHA'),
    ('MARTHA WANGUI'),
    ('Martin Kubai'),
    ('Martin waweru'),
    ('MARY ANDIKA'),
    ('Matias Ndonga Kabiru'),
    ('MATILDA NIMATSUTSU'),
    ('Maureen Mulang’a'),
    ('Maureen Mulang''a'),
    ('Melissa Kasaba'),
    ('MERCY ATEKA'),
    ('Mercy Kirema'),
    ('MICHAEL KYEVA'),
    ('Michael Nderitu'),
    ('Michael Odhiambo Okumu'),
    ('Michael Wanjohi'),
    ('MICHELLE OUMA'),
    ('MIKE IRAVO'),
    ('Mike Mutunga'),
    ('Millicent cherotich'),
    ('Miriam Mutunga'),
    ('MOHAMED MUNYANYA'),
    ('Mohamed Said'),
    ('MOHAMMED ALI MWENJE'),
    ('MOHAMMED HASSAN BARE'),
    ('Morris Muiruri Murigi'),
    ('MORRIS YAVI'),
    ('MOSES AKIDADI'),
    ('MOSES KIPTUI'),
    ('Moses Makori'),
    ('Muguru Wairimu'),
    ('Muhammad Ali'),
    ('Mutua Urbanos'),
    ('Mwongera Rukaria'),
    ('Naomi Achieng'''),
    ('NATHANIEL NGUITHI'),
    ('Ndindiri Waweru'),
    ('NELLY AGOLA'),
    ('NEROUS MUTCHERE'),
    ('NICHOLAS KIOGORA'),
    ('Nicholas Nyona'),
    ('Nicholas Onyango'),
    ('Nick Mungai'),
    ('NISHA VAN HOEK'),
    ('Obutu Ivan Magori'),
    ('Ogada Alice Awuor'),
    ('OGEMBO ENOCK'),
    ('OGUTU CYRUS'),
    ('Ojwang Bernard'),
    ('Oliver Chapa'),
    ('ONESMUS KAKOI MWATU'),
    ('Patricia Baariu'),
    ('Patrick Kathuli'),
    ('Patrick Mugo'),
    ('PATRICK OYONDI'),
    ('PAUL AYODI'),
    ('PAUL KARARA'),
    ('Paul Mumo'),
    ('PAUL MUTHOKA'),
    ('PAUL OUMA'),
    ('PAULINE MWASHI'),
    ('peninah omanwa'),
    ('PETER KANYI'),
    ('Peter Miriti'),
    ('Peter Njeru'),
    ('Philip Osoro Amwata'),
    ('Phires Ogoti'),
    ('Plan David Ore'),
    ('PLAN SIMON NJOROGE KAMAU'),
    ('PLAN. CHRISTINE MUCHIRI'),
    ('PROF TOM ANYAMBA'),
    ('Qs Morris Mwiti'),
    ('QS MUTINDA MUTUKU'),
    ('QS. AUDILY CHATORA'),
    ('QS. DAVID AGANYO NYANGAU'),
    ('QUEENVELLY MAYAKA'),
    ('REDEMPTA MUNYALO'),
    ('REHEMA JAYSHREE'),
    ('Restepice Rammoko'),
    ('Rither Chepkemoi'),
    ('ROBERT KIGGUNDU'),
    ('RODAH BOYANI'),
    ('RODGERS MWENDA'),
    ('RONALD MURIUKI'),
    ('ROSE KAGECHI WAWERU'),
    ('ROSEBRENDA MUCHIGA'),
    ('Roy Guda'),
    ('RUTH MAKAU'),
    ('Ryan Losieku'),
    ('SAMSON MAINA'),
    ('Samson Mutune'),
    ('Samuel Githae'),
    ('SAMUEL KIAI'),
    ('Sarah Kibe'),
    ('SAVIA MJOMBA'),
    ('SCOTT WAITHAKA'),
    ('Serah Chege'),
    ('SHARON TANUI'),
    ('SHEILA JEPKORIRI TANUI'),
    ('SHEILA OKONGO'),
    ('Silvester Muli'),
    ('SIMON KAGOTHO'),
    ('Solomon Were'),
    ('Stanley Gado'),
    ('Stanley Karanja'),
    ('Stanley Kyalo'),
    ('STANLEY NGENY'),
    ('STEPHEN MUCHERU'),
    ('STEPHEN MUTISO'),
    ('STEPHEN MWILU'),
    ('Steve Gome'),
    ('STEVE MAHONGA'),
    ('SUSAN NJERI KIBUE'),
    ('SYLVIA ESSENDI'),
    ('SYMMON KIDERO'),
    ('Syrone Owuor Otieno'),
    ('TAMASHA WAMBUI NDUNG’U'),
    ('TOBIAS JOSEPH'),
    ('Tuesday Nyakango'),
    ('Valerie Gatwiri Irungu'),
    ('Victor Bielesie'),
    ('VICTOR KANYAURA'),
    ('VICTOR KIVAYA'),
    ('VICTOR NJIRU'),
    ('VICTORIA BANCHIRI'),
    ('Viola Adhiambo Sigu'),
    ('VIOLET BAGADA'),
    ('Vivian Wambui Thairu'),
    ('Wageita Peter Munyua'),
    ('WAMBAA MUNGAI'),
    ('WELLINGTON SINDANI'),
    ('Wendy Kihiu'),
    ('Wesly Asubwa'),
    ('WILLIAM MAMBO MATOLA'),
    ('Wilson Mugambi'),
    ('WILSON NYANGE'),
    ('Winfrida Wanjiku Ngumi'),
    ('WINNIE KALYA'),
    ('WINSTON SHIMIRWA'),
    ('WYCLIFFE OMARIBA'),
    ('ZAWADI NDUNG’U')
    ) as t(full_name) on public.normalize_name(d.full_name) = public.normalize_name(t.full_name)
    where d.event_id = public.active_event_id();
  raise notice 'Target names: %, matched delegates: %', v_target_count, v_matched_count;
end $$;
