// This file is automatically generated. Do not edit it directly.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      audit_events: {
        Row: {
          action: string
          actor_email: string | null
          actor_id: string | null
          created_at: string
          entity_id: string | null
          entity_type: string | null
          id: string
          metadata: Json
        }
        Insert: {
          action: string
          actor_email?: string | null
          actor_id?: string | null
          created_at?: string
          entity_id?: string | null
          entity_type?: string | null
          id?: string
          metadata?: Json
        }
        Update: {
          action?: string
          actor_email?: string | null
          actor_id?: string | null
          created_at?: string
          entity_id?: string | null
          entity_type?: string | null
          id?: string
          metadata?: Json
        }
        Relationships: []
      }
      client_errors: {
        Row: {
          actor_email: string | null
          actor_id: string | null
          context: Json
          created_at: string
          id: string
          message: string
          path: string | null
          stack: string | null
        }
        Insert: {
          actor_email?: string | null
          actor_id?: string | null
          context?: Json
          created_at?: string
          id?: string
          message: string
          path?: string | null
          stack?: string | null
        }
        Update: {
          actor_email?: string | null
          actor_id?: string | null
          context?: Json
          created_at?: string
          id?: string
          message?: string
          path?: string | null
          stack?: string | null
        }
        Relationships: []
      }
      check_ins: {
        Row: {
          checked_in_at: string
          checked_in_by: string | null
          delegate_id: string
          device_label: string | null
          id: string
          method: Database["public"]["Enums"]["check_in_method"]
          notes: string | null
        }
        Insert: {
          checked_in_at?: string
          checked_in_by?: string | null
          delegate_id: string
          device_label?: string | null
          id?: string
          method: Database["public"]["Enums"]["check_in_method"]
          notes?: string | null
        }
        Update: {
          checked_in_at?: string
          checked_in_by?: string | null
          delegate_id?: string
          device_label?: string | null
          id?: string
          method?: Database["public"]["Enums"]["check_in_method"]
          notes?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "check_ins_delegate_id_fkey"
            columns: ["delegate_id"]
            isOneToOne: true
            referencedRelation: "delegates"
            referencedColumns: ["id"]
          },
        ]
      }
      delegates: {
        Row: {
          badge_code: string
          badge_token: string
          created_at: string
          email: string | null
          event_id: string
          full_name: string
          id: string
          import_batch_id: string | null
          organization: string | null
          phone: string | null
          photo_consent: boolean | null
          source: Database["public"]["Enums"]["delegate_source"]
          status: Database["public"]["Enums"]["delegate_status"]
          updated_at: string
        }
        Insert: {
          badge_code?: string
          badge_token?: string
          created_at?: string
          email?: string | null
          event_id: string
          full_name: string
          id?: string
          import_batch_id?: string | null
          organization?: string | null
          phone?: string | null
          photo_consent?: boolean | null
          source?: Database["public"]["Enums"]["delegate_source"]
          status?: Database["public"]["Enums"]["delegate_status"]
          updated_at?: string
        }
        Update: {
          badge_code?: string
          badge_token?: string
          created_at?: string
          email?: string | null
          event_id?: string
          full_name?: string
          id?: string
          import_batch_id?: string | null
          organization?: string | null
          phone?: string | null
          photo_consent?: boolean | null
          source?: Database["public"]["Enums"]["delegate_source"]
          status?: Database["public"]["Enums"]["delegate_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "delegates_import_batch_id_fkey"
            columns: ["import_batch_id"]
            isOneToOne: false
            referencedRelation: "import_batches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "delegates_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
        ]
      }
      import_batches: {
        Row: {
          created_at: string
          created_by: string | null
          errors: Json
          filename: string
          id: string
          inserted: number
          skipped: number
          total_rows: number
          updated: number
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          errors?: Json
          filename: string
          id?: string
          inserted?: number
          skipped?: number
          total_rows?: number
          updated?: number
        }
        Update: {
          created_at?: string
          created_by?: string | null
          errors?: Json
          filename?: string
          id?: string
          inserted?: number
          skipped?: number
          total_rows?: number
          updated?: number
        }
        Relationships: []
      }
      staff_profiles: {
        Row: {
          active: boolean
          created_at: string
          email: string
          full_name: string
          updated_at: string
          user_id: string
          username: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          email: string
          full_name: string
          updated_at?: string
          user_id: string
          username: string
        }
        Update: {
          active?: boolean
          created_at?: string
          email?: string
          full_name?: string
          updated_at?: string
          user_id?: string
          username?: string
        }
        Relationships: []
      }
      events: {
        Row: {
          active: boolean
          created_at: string
          created_by: string | null
          id: string
          name: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          created_by?: string | null
          id?: string
          name: string
        }
        Update: {
          active?: boolean
          created_at?: string
          created_by?: string | null
          id?: string
          name?: string
        }
        Relationships: []
      }
      user_roles: {
        Row: {
          created_at: string
          id: string
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          role?: Database["public"]["Enums"]["app_role"]
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      add_and_check_in: {
        Args: {
          p_device_label?: string
          p_email: string
          p_full_name: string
          p_organization: string
          p_phone?: string
        }
        Returns: Json
      }
      admin_create_event: { Args: { p_name: string }; Returns: Json }
      admin_delete_delegate: { Args: { p_delegate_id: string }; Returns: Json }
      admin_create_kiosk_token: { Args: never; Returns: string }
      admin_exists: { Args: never; Returns: boolean }
      admin_log_password_reset: { Args: { p_user_id: string }; Returns: undefined }
      admin_get_active_kiosk_token: { Args: never; Returns: string }
      admin_provision_staff: {
        Args: {
          p_email: string
          p_full_name: string
          p_role?: Database["public"]["Enums"]["app_role"]
          p_user_id: string
          p_username: string
        }
        Returns: Json
      }
      admin_set_active_event: { Args: { p_event_id: string }; Returns: undefined }
      admin_set_staff_role: {
        Args: {
          p_grant: boolean
          p_role: Database["public"]["Enums"]["app_role"]
          p_user_id: string
        }
        Returns: Json
      }
      admin_update_staff: {
        Args: {
          p_active?: boolean
          p_full_name?: string
          p_user_id: string
          p_username?: string
        }
        Returns: Json
      }
      admin_delete_staff: { Args: { p_user_id: string }; Returns: Json }
      check_in_delegate: {
        Args: {
          p_device_label?: string
          p_lookup: string
          p_method: Database["public"]["Enums"]["check_in_method"]
          p_notes?: string
        }
        Returns: Json
      }
      claim_first_admin: {
        Args: { p_email: string; p_full_name: string; p_user_id: string; p_username: string }
        Returns: boolean
      }
      active_event_id: { Args: never; Returns: string }
      dashboard_stats: { Args: never; Returns: Json }
      generate_badge_code: { Args: never; Returns: string }
      has_role: {
        Args: {
          _role: Database["public"]["Enums"]["app_role"]
          _user_id: string
        }
        Returns: boolean
      }
      import_delegates: {
        Args: { p_filename: string; p_rows: Json }
        Returns: Json
      }
      is_active_admin: { Args: { _user_id: string }; Returns: boolean }
      is_active_staff: { Args: { _user_id: string }; Returns: boolean }
      kiosk_check_in: {
        Args: {
          p_email?: string
          p_full_name: string
          p_organization?: string
          p_photo_consent?: boolean
          p_token: string
        }
        Returns: Json
      }
      normalize_name: { Args: { p: string }; Returns: string }
      log_client_error: {
        Args: { p_context?: Json; p_message: string; p_path?: string; p_stack?: string }
        Returns: undefined
      }
      log_audit: {
        Args: {
          _action: string
          _entity_id: string
          _entity_type: string
          _metadata: Json
        }
        Returns: undefined
      }
      public_create_badge: {
        Args: {
          p_email: string
          p_full_name: string
          p_organization: string
          p_phone?: string
        }
        Returns: Json
      }
      public_find_badge: { Args: { p_email: string }; Returns: Json }
      public_get_badge: { Args: { p_token: string }; Returns: Json }
      remove_test_delegates: { Args: never; Returns: number }
      resolve_staff_login: { Args: { p_username: string }; Returns: string }
      undo_check_in: { Args: { p_delegate_id: string }; Returns: Json }
      update_delegate_details: {
        Args: {
          p_delegate_id: string
          p_email?: string
          p_organization?: string
          p_phone?: string
          p_photo_consent?: boolean
        }
        Returns: Json
      }
      update_own_full_name: { Args: { p_full_name: string }; Returns: Json }
      valid_email: { Args: { _email: string }; Returns: boolean }
    }
    Enums: {
      app_role: "admin" | "staff"
      check_in_method: "qr" | "search" | "walk_in" | "kiosk"
      delegate_source: "import" | "public" | "walk_in"
      delegate_status: "expected" | "checked_in"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      app_role: ["admin", "staff"],
      check_in_method: ["qr", "search", "walk_in", "kiosk"],
      delegate_source: ["import", "public", "walk_in"],
      delegate_status: ["expected", "checked_in"],
    },
  },
} as const
